name: recipe_x
description: "RecipeX is a recipe app that allows users to search for recipes, view details, and save their favorite recipes."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  go_router: ^14.0.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11+1
  adaptive_screen_utils: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - recipes/
    - assets/svgs/
